:revdate: 2022-07-10
= https://hackage.haskell.org/package/singletons[Singletons] in Haskell

If you are deep into Haskell you've probably come across the https://hackage.haskell.org/package/singletons[singletons] library.
You may have shied away, because it looked scary, but really the main concept is actually quite straight-forward.

TIP: If you are willing to spend a bit of time to understand the ins and outs of this library, you should read this https://richarde.dev/papers/2012/singletons/paper.pdf[paper] by Richard A. Eisenberg and Stephanie Weirich.

== Why does this library exist?

Haskell doesn't have first class dependent types.
This library still allows you to write dependent functions.

== The main idea

A singleton type is a type with exactly one constructor.

.To write dependent functions in Haskell you have to use the singleton type to ...
1. promote a value to the type level.
2. demote a type-level constructor to value-level.

IMPORTANT: Now look at this table!

.Singleton for `Succ Nat`
[cols="1,3,3,3"]
|===
| kinds
|
| promoted kind: +
`Nat`
|

| types
| regular ADT: +
`Nat`
| type-level constructor: +
`'Succ 'Zero`
| singleton type: +
`SNat ('Succ 'Zero)`

| terms
| regular value constructor: +
`Succ Zero`
|
| singleton constructor: +
`SSucc SZero`
|===

The singleton type allows you to convert between types and terms.

[TIP]
====
If you understood this quite well, you have already grasped the main point of this library.
If you want to actually use the library to write Dependent Haskell, I once again recommend this https://richarde.dev/papers/2012/singletons/paper.pdf[paper] to get a bit more comfortable with the matter.
====

=== Why do we need a library, if the concept is so simple?

With the https://hackage.haskell.org/package/singletons[singletons] library you can use __TemplateHaskell__ to generate the singleton types for you.

CAUTION: Writing the singletons manually is really quite annoying!

It also gives names to common idioms, so it will actually help you to gain an understanding for dependent types in Haskell.
