name: "Default"
on:
  push:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output:
          [ packages.x86_64-linux.default
          , defaultConfigFile.x86_64-linux
          , devShell.x86_64-linux
          , packages.x86_64-linux.blog
          , packages.x86_64-linux.files
          , packages.x86_64-linux.homepage
          , packages.x86_64-linux.static
          ]
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2.4.0
    - name: "Set up nix"
      uses: cachix/install-nix-action@v15
    - name: "Build"
      run: nix build --print-build-logs .\#${{ matrix.output }}
  check:
    name: "Check Flake"
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2.4.0
    - name: "Set up nix"
      uses: cachix/install-nix-action@v15
    - name: "Check"
      run: nix flake check --keep-going --print-build-logs
  # TODO: Run weeder using `nix flake check` instead.
  weeder:
    name: "Detect dead code"
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2.4.0
    - name: "Set up nix"
      uses: cachix/install-nix-action@v15
    - name: "Prepare weeder"
      run: nix develop --command cabal build all
    - name: "Run weeder"
      run: nix develop --command weeder
